apiVersion: v2
name: redis-store
description: Succinct SP1 Cluster Redis Artifact Store.

dependencies:
  - name: redis
    version: 20.13.1 # uses Redis version 7.4.2
    repository: "oci://registry-1.docker.io/bitnamicharts"

version: 0.1.3
