appName: gpu-node

replicaCount: 1

image:
  repository: ghcr.io/succinctlabs/sp1-cluster
  pullPolicy: IfNotPresent
  tag: client-gpu-a00f4c4

spec:
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: "100%"

# Expose metrics server to cluster
services:
  - name: metrics
    type: ClusterIP
    port: 9090
    targetPort: 9090

extraEnv:

extraEnvFrom: []

resources:
  requests: {}
  limits: {}

nodeSelector: {}

tolerations: []

affinity: {}
