appName: cpu-node

replicaCount: 0

image:
  repository: ghcr.io/succinctlabs/sp1-cluster
  # repository: 421253708207.dkr.ecr.us-east-2.amazonaws.com/succinct-cluster
  pullPolicy: IfNotPresent
  tag: client-gpu-a00f4c4

# Expose metrics server to cluster
services:
  - name: metrics
    type: ClusterIP
    port: 9090
    targetPort: 9090

extraEnv: {}

extraEnvFrom: []

# Volume configuration
volumes:

volumeMounts:

resources:
  requests: {}
  limits: {}

nodeSelector: {}

tolerations: []

affinity: {}
