[package]
name = "sp1-cluster-node"
version = "0.1.0"
edition = "2021"

[features]
default = ["native-gnark"]
native-gnark = ["sp1-sdk/native-gnark"]
gpu = ["dep:moongate-prover", "sp1-cluster-worker/gpu"]

[dependencies]
moongate-prover = { workspace = true, optional = true }
sp1-cluster-artifact.workspace = true
sp1-cluster-common.workspace = true
sp1-cluster-worker.workspace = true
sp1-prover.workspace = true
sp1-sdk.workspace = true

cfg-if.workspace = true
ctrlc.workspace = true
dashmap.workspace = true
dirs.workspace = true
dotenv.workspace = true
eyre.workspace = true
flate2.workspace = true
jemallocator.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
rand.workspace = true
reqwest.workspace = true
serde_json.workspace = true
sysinfo.workspace = true
tar.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
