[package]
name = "sp1-cluster-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode.workspace = true
clap.workspace = true
dotenv.workspace = true
eyre.workspace = true
opentelemetry_sdk.workspace = true
sp1-cluster-artifact = { workspace = true }
sp1-cluster-utils = { workspace = true }
sp1-cluster-common = { workspace = true }
sp1-cluster-worker = { workspace = true }
sp1-core-executor = { workspace = true }
sp1-sdk = { workspace = true, features = ["native-gnark"] }
sp1-prover = { workspace = true }
sp1-prover-types = { workspace = true }
tokio.workspace = true
tracing.workspace = true

either = { version = "1.15.0", features = ["serde"] }
rand = "0.8"
serde_json = { workspace = true }
