appName: fulfiller

replicaCount: 1

image:
  repository: ghcr.io/succinctlabs/sp1-cluster
  pullPolicy: IfNotPresent
  tag: base-v2.0.3

extraEnv: {}

extraEnvFrom: []

resources:
  requests: {}
  limits: {}

nodeSelector: {}

tolerations: []

affinity: {}
